### ISSUE TITLE
Invalid value "" for configuration advertised.port

### ISSUE THREAD

**Issue by m99coder** [argussecurity/docker-kafka-prometheus#1]
Hi Alon,

I’m using your docker image to run the following command:

```bash
$ docker run -p 9092:9092 -p 8080:8080 -e "KAFKA_OPTS=-javaagent:/usr/app/jmx_prometheus_javaagent.jar=8080:/usr/app/prometheus-config.yml" argussecurity/kafka-prometheus:0.10.1.0
```

It’s failing with the following error message:

```bash
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
waiting for kafka to be ready
2017-05-24 10:11:21.955:INFO:ipjsoejs.Server:jetty-8.y.z-SNAPSHOT
2017-05-24 10:11:22.062:INFO:ipjsoejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:8080
[2017-05-24 10:11:22,856] FATAL  (kafka.Kafka$)
org.apache.kafka.common.config.ConfigException: Invalid value  for configuration advertised.port: Not a number of type INT
	at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:669)
	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:418)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:56)
	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:795)
	at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:779)
	at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:776)
	at kafka.server.KafkaServerStartable$.fromProps(KafkaServerStartable.scala:28)
	at kafka.Kafka$.main(Kafka.scala:58)
	at kafka.Kafka.main(Kafka.scala)
```

My docker version is `Docker version 17.03.1-ce, build c6d412e` on macOS 10.12.4 (16E195).

Can you help in any way?

All the best,
Marco

**Comment by alonl** [comment]
Hi Marco,

This issue is not related to this (kafka-prometheus) image, but to the original (wurstmeister/kafka) image.

Running `docker run -p 9092:9092 -p 8080:8080 wurstmeister/kafka:0.10.1.0` returns exactly the same error:
```
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
waiting for kafka to be ready
[2017-05-26 10:25:58,940] FATAL  (kafka.Kafka$)
org.apache.kafka.common.config.ConfigException: Invalid value  for configuration advertised.port: Not a number of type INT
	at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:669)
	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:418)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:56)
	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:795)
	at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:779)
	at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:776)
	at kafka.server.KafkaServerStartable$.fromProps(KafkaServerStartable.scala:28)
	at kafka.Kafka$.main(Kafka.scala:58)
	at kafka.Kafka.main(Kafka.scala)
```

A quick fix for this can be adding `-e KAFKA_ADVERTISED_PORT=9092` to your command, e.g.
```
docker run -p 9092:9092 -p 8080:8080 -e KAFKA_ADVERTISED_PORT=9092 -e "KAFKA_OPTS=-javaagent:/usr/app/jmx_prometheus_javaagent.jar=8080:/usr/app/prometheus-config.yml" argussecurity/kafka-prometheus:0.10.1.0
```

Notice that you'll now probably get a different error - ` Unable to connect to zookeeper`... so you'll probably have to add `-e KAFKA_ZOOKEEPER_CONNECT=<zookeeper_address>:2181`.

I suggest to read [wurstmeister/kafka](https://github.com/wurstmeister/kafka-docker/) documentation.

Good luck!
